In [1]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [4]:
df = pd.read_csv('model-selection-clean.csv', index_col = 0)

In [5]:
df.head()

,SCHOOL,STATE,ID,ABBR,COUNTY,CHARTER,MAGNET,LOCALE,TITLE I,TITLE I ELIGIBLE,...,AMERICAN INDIAN,ASIAN,HISPANIC,BLACK,WHITE,TOTAL RACE/ETHINICITY,FTE TEACHERS,PUPIL-TEACHER RATIO,FREE LUNCH ELIGIBLE NUMERIC,REDUCED PRICE LUNCH ELIGIBLE NUMERIC
1,10TH STREET SCHOOL,Washington,5.304860e+11,WA,Snohomish County,2-No,–,22-Suburb: Mid-size,1-Yes,1-Yes,...,8,5,20,1,122,0,0,0,28.0,3.0
2,112 ALC INDEPENDENT STUDY,Minnesota,2.708190e+11,MN,Carver County,2-No,2-No,21-Suburb: Large,†,2-No,...,0,1,10,0,22,0,0,0,8.0,3.0
3,112 ALC MIDDLE SCHOOL,Minnesota,2.708190e+11,MN,Carver County,2-No,2-No,21-Suburb: Large,†,2-No,...,0,5,32,8,82,0,0,0,54.0,7.0
4,12TH STREET ELEMENTARY,Michigan,2.628950e+11,MI,Kalamazoo County,2-No,2-No,13-City: Small,†,2-No,...,0,68,27,48,406,0,0,0,99.0,21.0
6,1R ELEMENTARY,Nebraska,3.174580e+11,NE,Hall County,†,†,41-Rural: Fringe,†,2-No,...,1,0,12,3,155,0,13,0,15.0,30.0